name: CI
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node js
        id: cache-nodejs
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/node
          key: node_19.9.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
      - name: Run tests
        run: |
          which node
          echo $HOME