name: CI
on: [push]
env:
  NODE_VERSION: 17.0.1
  RUBY_VERSION: 3.1.2

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
      - name: Run tests
        run: |
          which node